# Generated by Django 5.0.6 on 2025-01-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='club_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('spouse_name', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('phone_office', models.CharField(max_length=15)),
                ('phone_residence', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('membership_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
